HRMVC/Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using HRMVC.Models;
using System.Data.Entity;
using System.Net;
using DataAccess;

namespace HRMVC.Controllers
{
    public class CampaignController : BaseController
    {
        // VIEW Return Campaigns view with DataTables Grid
        public ActionResult Index()
        {
            return View();
        }

        // GET Return Campaign speicified by CampaignID value
        public async Task<JsonResult> GetCampaign(int? id)
        {

            if (id == null)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest), JsonRequestBehavior.AllowGet);
            }


            Campaign c = await DataContext.Campaigns.FindAsync(id);
            if (c == null)
            {
                return Json(HttpNotFound(), JsonRequestBehavior.AllowGet);
            }

            CampaignViewModel campaign = new CampaignViewModel();

            campaign.CampaignID = c.CampaignID;
            campaign.Name = c.Name;
            campaign.DateStarted = c.DateStarted;
            campaign.DateFinished = c.DateFinished;
            campaign.Description = c.Description;
            campaign.Created = c.Created;
            campaign.CreatedBy = c.CreatedBy;
            campaign.LastUpdated = c.LastUpdated;
            campaign.LastUpdatedBy = c.LastUpdatedBy;

            return Json(campaign, JsonRequestBehavior.AllowGet);
        }


        //GET Get all campaigns from campaigns DataSet
        public async Task<JsonResult> GetCampaigns()
        {
            var campaigns = await DataContext.Campaigns
                    .Select(c => new CampaignViewModel
                    {
                        CampaignID = c.CampaignID,
                        Name = c.Name,
                        DateStarted = c.DateStarted,
                        DateFinished = c.DateFinished,
                        Description = c.Description,
                        CreatedBy = c.CreatedBy,
                        LastUpdated = c.LastUpdated,
                        LastUpdatedBy = c.LastUpdatedBy
                    }).ToListAsync();

            return Json(campaigns, JsonRequestBehavior.AllowGet);
        }

        //GET Get all campaigns from campaigns DataSet with candidates and their current statuses
        public async Task<JsonResult> GetCampaignsComplete()
        {

            //get all campaigns with candidates and statuses
            var campaignsQuery = await DataContext.Campaigns
                            .Include(c => c.CampaignsCandidatesStatuses.Select(cd => cd.Candidate))
                            .Include(c => c.CampaignsCandidatesStatuses.Select(st => st.Status))
                            .Select(x => new CampaignViewModel
                            {
                                CampaignID = x.CampaignID,
                                DateStarted = x.DateStarted,
                                DateFinished = x.DateFinished,
                                Name = x.Name,
                                Created = x.Created,
                                CreatedBy = x.CreatedBy,
                                Description = x.Description,
                                LastUpdated = x.LastUpdated,
                                LastUpdatedBy = x.LastUpdatedBy,
                            })
                            .ToListAsync();

            return Json(campaignsQuery, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> GetAssignedCandidates(int? id)
        {
            string message;

            if (id == null)
            {
                message = "Bad request: Invalid data sent from client";
                return Json(new { success = false, message }, JsonRequestBehavior.AllowGet);
            }

            //check if campaign exists
            if (!(await EvaluationHelpers.CheckCampaignByID(DataContext, id ?? default(int))))
            {
                message = "Error: Could not fetch candidates, no campaigns with matching ID found";
                return Json(new { success = false, message }, JsonRequestBehavior.AllowGet);
            }

            List<AssignedCandidateViewModel> candidates = new List<AssignedCandidateViewModel>();

                candidates = DataContext.CampaignsCandidatesStatuses
                                    .Include(x => x.Candidate.CandidatesExpertisesLevels.Select(e => e.Expertise))
                                    .Where(c => (c.CampaignID == id && c.Deleted == null))
                                    .GroupBy(c => c.CandidateID)
                                    .Select(g => g.OrderByDescending(c => c.Created)
                                    .Select(y => new AssignedCandidateViewModel
                                    {
                                        CandidateID = y.CandidateID,
                                        FirstName = y.Candidate.FirstName,
                                        LastName = y.Candidate.LastName,
                                        LastStatus = y.Status.Name,
                                        PrimaryExpertise = y.Candidate.CandidatesExpertisesLevels.Where(x => x.IsPrimary).Select(x => x.Expertise.Name).FirstOrDefault()
                                    })
                                    .FirstOrDefault()).ToList();


            return Json(candidates, JsonRequestBehavior.AllowGet);
        }

        //POST Create new campaign
        //[ValidateAntiForgeryToken]
        [HttpPost]
        [ValidateModel]
        public async Task<JsonResult> CreateCampaign(CampaignViewModel campaign)
        {
            string message;

            if (campaign.DateStarted >= campaign.DateFinished)
            {
                message = "Error: Start date can't be later or on the same day as finish date!";
                return Json(new { success = false, message }, JsonRequestBehavior.AllowGet);
            }

            Campaign c = new Campaign();

            c.DateStarted = campaign.DateStarted;
            c.DateFinished = campaign.DateFinished.AddHours(23).AddMinutes(59);
            c.Description = campaign.Description;
            c.CreatedBy = User.Identity.Name;
            c.Created = DateTime.Now;
            c.Name = campaign.Name;

            DataContext.Campaigns.Add(c);
            await DataContext.SaveChangesAsync();

            message = "Success: Campaign " + c.Name + " created!";
            return Json(new { success = true, message }, JsonRequestBehavior.AllowGet);
        }

        // POST Campaigns/EditCampaign/5 Edit Campaign
        [HttpPost]
        [ValidateModel]
        public async Task<JsonResult> EditCampaign(CampaignViewModel campaign)
        {

            string message;

            if (campaign == null)
            {
                message = "Bad request: Invalid data sent from client";
                return Json(new { success = false, message }, JsonRequestBehavior.AllowGet);
            }

            if (campaign.DateStarted >= campaign.DateFinished)
            {
                message = "Error: Start date can't be later or on the same day as finish date!";
                return Json(new { success = false, message }, JsonRequestBehavior.AllowGet);
            }

            var c = await DataContext.Campaigns
                                 .Where(x => x.CampaignID == campaign.CampaignID)
                                 .FirstOrDefaultAsync();

                if (c == null)
                {
                    message = "Error: Could not update specified campaign, no campaigns with matching ID found";
                    return Json(new { success = false, message }, JsonRequestBehavior.AllowGet);
                }

                c.Name = campaign.Name;
                c.DateStarted = campaign.DateStarted;
                c.DateFinished = campaign.DateFinished.AddHours(23).AddMinutes(59);
                c.Description = campaign.Description;
                c.LastUpdated = DateTime.Now;
                c.LastUpdatedBy = User.Identity.Name;

                await DataContext.SaveChangesAsync();

            message = "Success: Campaign " + c.Name + " updated!";
            return Json(new { success = true, message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Assign()
        {
            return View();
        }

        //Return valid statuses that a candidate can have in a campaign
        [HttpPost]
        [ValidateModel]
        public async Task<JsonResult> ReturnValidStatuses(CampaignStatusAssignmentViewModel assignment)
        {
            string message;

            var currentCampaign = await DataContext.Campaigns
                                                    .Where(c => c.CampaignID == assignment.CampaignID)
                                                    .SingleOrDefaultAsync();


            //check if campaign is finished
            if (await EvaluationHelpers.CheckCampaignFinished(DataContext, currentCampaign.CampaignID))
            {
                message = "Campaign finished, no changes in this campaign can be made now";
                return Json(new { success = false, message }, JsonRequestBehavior.AllowGet);
            }

            var mostRecentStatus = await DataContext.CampaignsCandidatesStatuses
                                                .Include(e => e.Status)
                                                .Where(c => (c.CandidateID == assignment.CandidateID && c.CampaignID == assignment.CampaignID))
                                                .OrderByDescending(a => a.Created)
                                                .FirstOrDefaultAsync();

            var statuses = await DataContext.Statuses
                                .Where(s => s.Priority > mostRecentStatus.Status.Priority)
                                .Select(s => new StatusViewModel

HRMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HR Manager - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    @{
        var theme = Session["CssTheme"] as string ?? HRMVC.Helpers.Bootstrap.Theme.flatly;
        var navbarType = Session["NavbarType"] as string ?? "navbar navbar-inverse navbar-fixed-top";
    }

    @Styles.Render(HRMVC.Helpers.Bootstrap.Bundle(theme))
    
</head>
<body>
    <div class="@navbarType">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HR Portal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Candidates", "Index", "Candidate")
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Campaigns<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Assign candidates", "Assign", "Campaign")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Companies", "Companies", "Settings")</li>
                            <li>@Html.ActionLink("Expertises", "Expertises", "Settings")</li>
                            <li>@Html.ActionLink("Skills", "Levels", "Settings")</li>
                            <li>@Html.ActionLink("Statuses", "Statuses", "Settings")</li>
                            <li>@Html.ActionLink("User Options", "Index", "Manage")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <!--<p>&copy; @*DateTime.Now.Year*@</p>-->

        </footer>

            </footer>
        </div>

        @Scripts.Render("~/bundles/bootstrap")
        @Styles.Render("~/Content/themes/base/css")
        @RenderSection("scripts", required: false)
    </body>
</html>